### ISSUE TITLE
Where is the save data stored at?

### ISSUE THREAD

**Issue by Eris7090** [Nightmayr-snaps/ppsspp-snap#4]
I wanna transfer my save from retroarch to this but this file stucture is so confusing

**Comment by Eris7090** [comment]
I've looked everywhere now I am a broken man

**Comment by Nightmayr** [comment]
Hi sorry, didnt see this until now. The save data for the ppsspp snap is located under `~/snap/ppsspp-emu/common/.config/ppsspp/PSP`
